name: Setup Autoit Compiler Toolkit
description: 'Windows setup "Autoit Compiler Toolkit"'
branding: 
  icon: 'package'
  color: 'blue'

runs:
  using: "composite"
  steps:
    - name: Install Dependencies (Windows)
      run: ${{ github.action_path }}/install.ps1
      shell: pwsh